### ISSUE TITLE
Experiments on the performance of different tokenizers

### ISSUE THREAD

**Issue by KehanChen510** [zhangtaolab/Plant_DNA_LLMs#10]
Excuse me, where can I get the results for all the different tokenizers? I've only seen optimal tokenizer results so far.

**Comment by ljq12697** [comment]
In the PDLLMs website,  you can choose whether or not to use the recommended model for different tasks by selecting the 'No' button. Besides, we have provided the models with different tokenizers on Hugging face and ModelScope.

**Comment by KehanChen510** [comment]
Thank you for your reply. I mainly want to see the performance difference of different tokenizers on the downstream tasks mentioned in the paper, but Figure 1E only shows the best results. Do you have performance results for all the tokenizers?

**Comment by ljq12697** [comment]
All the performances of different models and tokenizers have shown in the Supplemental Table 2, also the comparison among different tokenizers was exhibited in Supplemental figure 3 and 4.

**Comment by KehanChen510** [comment]
Could you send me the link to the supplement? I couldn't find the corresponding link on ScienceDirect.

**Comment by ljq12697** [comment]
Sorry, I didn't find the links for supplemental information on ScienceDirect, the article is in press now.

I can provide the supplemental figure3 for reference, maybe you can wait for the publication of our manuscript.
![sf3](https://github.com/user-attachments/assets/fa03bf2e-a2db-4e2a-afc3-98d2e87ac97f)

**Comment by KehanChen510** [comment]
OK. Thanks!
